name: Increment Page Views

on:
  push:
    branches:
      - main

jobs:
  increment-counter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Increment page views
        run: |
          FILE="counter.txt"
          if [ -f "$FILE" ]; then
            COUNT=$(cat $FILE)
            COUNT=$((COUNT + 1))
            echo $COUNT > $FILE
          else
            echo "1" > $FILE
          fi

      - name: Commit changes
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automatische Inkrementierung der Seitenaufrufe"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
